DEBUG 2024-06-03 23:52:14,528 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-03 23:52:59,509 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-03 23:54:28,511 log Not Found: /api/gcp/instances/terminate/
WARNING 2024-06-03 23:55:51,419 log Not Found: /api/api/gcp/instances/
WARNING 2024-06-03 23:56:13,313 log Not Found: /api/gcp/instances/
WARNING 2024-06-03 23:56:24,814 log Not Found: /api/v0/gcp/instances/
DEBUG 2024-06-03 23:56:40,409 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-04 01:00:26,897 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-04 01:01:38,250 log Method Not Allowed: /api/v0/configurations/store_secret/
ERROR 2024-06-04 01:02:37,300 log Internal Server Error: /api/v0/configurations/store_secret
Traceback (most recent call last):
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/v0/configurations/store_secret/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2024-06-04 01:02:44,377 log Internal Server Error: /api/v0/configurations/store_secret/
Traceback (most recent call last):
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/Workspace/ilef_cloud/configurations/views.py", line 43, in store_secret
    vault_service.store_secret(path, secret_data)
  File "/home/mahrezbh/Desktop/pfe/Workspace/ilef_cloud/configurations/services/vault_service.py", line 13, in store_secret
    self.client.secrets.kv.v2.create_or_update_secret(
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/hvac/api/secrets_engines/kv_v2.py", line 126, in create_or_update_secret
    return self._adapter.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/hvac/adapters.py", line 110, in post
    return self.request('post', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/hvac/adapters.py", line 353, in request
    response = super(JSONAdapter, self).request(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/hvac/adapters.py", line 315, in request
    utils.raise_for_error(
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/hvac/utils.py", line 43, in raise_for_error
    raise exceptions.InvalidPath(message, errors=errors, method=method, url=url)
hvac.exceptions.InvalidPath: no handler for route 'secret/data/secret/example1', on post http://65.21.242.144:8200/v1/secret/data/secret/example1
WARNING 2024-06-04 01:02:56,890 log Bad Request: /api/v0/configurations/store_secret/
ERROR 2024-06-04 01:03:05,358 log Internal Server Error: /api/v0/configurations/store_secret/
Traceback (most recent call last):
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/Workspace/ilef_cloud/configurations/views.py", line 43, in store_secret
    vault_service.store_secret(path, secret_data)
  File "/home/mahrezbh/Desktop/pfe/Workspace/ilef_cloud/configurations/services/vault_service.py", line 13, in store_secret
    self.client.secrets.kv.v2.create_or_update_secret(
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/hvac/api/secrets_engines/kv_v2.py", line 126, in create_or_update_secret
    return self._adapter.post(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/hvac/adapters.py", line 110, in post
    return self.request('post', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/hvac/adapters.py", line 353, in request
    response = super(JSONAdapter, self).request(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/hvac/adapters.py", line 315, in request
    utils.raise_for_error(
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/hvac/utils.py", line 43, in raise_for_error
    raise exceptions.InvalidPath(message, errors=errors, method=method, url=url)
hvac.exceptions.InvalidPath: no handler for route 'secret/data', on post http://65.21.242.144:8200/v1/secret/data
WARNING 2024-06-04 01:05:50,145 log Not Found: /store-secret/
WARNING 2024-06-04 01:06:17,662 log Not Found: /store-secret/
DEBUG 2024-06-04 21:55:04,463 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-04 21:55:30,680 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-04 21:56:14,276 log Not Found: /api/v0/configurations/fetch_secret
WARNING 2024-06-04 21:56:20,907 log Not Found: /api/v0/configurations/fetch_secret/
WARNING 2024-06-04 21:56:23,097 log Not Found: /api/v0/configurations/fetch_secret/s/
DEBUG 2024-06-04 21:57:22,615 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-04 21:57:24,505 log Not Found: /api/v0/configurations/fetch_secret/
WARNING 2024-06-04 21:57:26,371 log Not Found: /api/v0/configurations/fetch_secret
WARNING 2024-06-04 21:57:42,544 log Not Found: /api/v0/configurations/fetch_secret//
WARNING 2024-06-04 21:57:43,925 log Not Found: /api/v0/configurations/fetch_secret/
DEBUG 2024-06-04 21:58:44,448 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-04 21:58:47,744 log Not Found: /api/v0/configurations/fetch_secret/
WARNING 2024-06-04 21:59:09,399 log Not Found: /api/v0/configurations/fetch_secret/
DEBUG 2024-06-04 21:59:25,717 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-04 22:00:50,127 utils (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-04 22:00:55,694 log Not Found: /api/v0/configurations/fetch_secret/
DEBUG 2024-06-04 22:01:57,939 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-04 22:02:08,055 log Not Found: /api/v0/configurations/fetch_secret/AWS_ACCESS_KEY_ID/
DEBUG 2024-06-04 22:02:57,262 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-04 22:02:59,370 log Not Found: /api/v0/configurations/fetch_secret/AWS_ACCESS_KEY_ID/
DEBUG 2024-06-04 22:03:11,590 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-04 22:04:27,298 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-04 22:04:43,279 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-04 22:05:02,575 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-04 22:05:24,958 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-04 22:05:35,115 log Not Found: /api/v0/configurations/fetch_secret/
DEBUG 2024-06-04 22:05:55,559 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-04 22:06:01,002 log Not Found: /api/v0/configurations/fetch_secret/
DEBUG 2024-06-04 22:06:17,945 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-04 22:06:20,241 log Not Found: /api/v0/configurations/fetch_secret/
WARNING 2024-06-04 22:06:30,713 log Not Found: /api/v0/configurations/fetch_secret/
WARNING 2024-06-04 22:06:34,442 log Not Found: /api/v0/configurations/fetch_secret/
DEBUG 2024-06-04 22:06:47,776 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-04 23:47:39,619 log Internal Server Error: /api/v0/configurations/fetch_secret/
DEBUG 2024-06-05 00:02:02,886 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 00:02:53,373 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 00:03:02,257 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 00:14:18,442 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 00:14:27,077 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 00:15:02,655 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 00:15:10,305 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 00:24:42,891 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-05 00:25:14,052 log Internal Server Error: /api/v0/aws/ec2/instances/create/
Traceback (most recent call last):
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/Workspace/ilef_cloud/cloud_providers/views.py", line 33, in post
    aws_manager = AWSManager()
                  ^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/Workspace/ilef_cloud/cloud_providers/services/aws_manager.py", line 16, in __init__
    self.ec2 = self.session.client('ec2')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/client.py", line 520, in _get_client_args
    return args_creator.get_client_args(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/args.py", line 100, in get_client_args
    final_args = self.compute_client_args(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/args.py", line 219, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/args.py", line 369, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/args.py", line 474, in _resolve_endpoint
    return endpoint_bridge.resolve(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/client.py", line 625, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/regions.py", line 229, in construct_endpoint
    result = self._endpoint_for_partition(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/regions.py", line 277, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
ERROR 2024-06-05 00:25:48,316 log Internal Server Error: /api/v0/configurations/fetch_secret/
ERROR 2024-06-05 00:27:20,640 log Internal Server Error: /api/v0/aws/ec2/instances/create/
Traceback (most recent call last):
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/Workspace/ilef_cloud/cloud_providers/views.py", line 33, in post
    aws_manager = AWSManager()
                  ^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/Workspace/ilef_cloud/cloud_providers/services/aws_manager.py", line 16, in __init__
    self.ec2 = self.session.client('ec2')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/session.py", line 997, in create_client
    client = client_creator.create_client(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/client.py", line 161, in create_client
    client_args = self._get_client_args(
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/client.py", line 520, in _get_client_args
    return args_creator.get_client_args(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/args.py", line 100, in get_client_args
    final_args = self.compute_client_args(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/args.py", line 219, in compute_client_args
    endpoint_config = self._compute_endpoint_config(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/args.py", line 369, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/args.py", line 474, in _resolve_endpoint
    return endpoint_bridge.resolve(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/client.py", line 625, in resolve
    resolved = self.endpoint_resolver.construct_endpoint(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/regions.py", line 229, in construct_endpoint
    result = self._endpoint_for_partition(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/botocore/regions.py", line 277, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
DEBUG 2024-06-05 00:27:35,353 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 16:03:49,266 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 16:06:57,993 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 16:11:30,895 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 16:14:53,046 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-05 16:15:26,415 log Bad Request: /api/v0/gcp/instances/create/
DEBUG 2024-06-05 16:18:07,031 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 16:18:21,106 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 22:21:45,589 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 22:23:54,820 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 22:26:41,692 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 22:39:22,883 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 22:41:37,907 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 22:41:42,614 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 22:41:49,216 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-05 22:42:50,081 log Internal Server Error: /api/v0/azure/instances/create/
Traceback (most recent call last):
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type VirtualMachine is not JSON serializable
DEBUG 2024-06-05 22:43:46,292 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-05 23:52:06,161 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 10:04:19,586 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 12:35:43,113 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 12:37:47,449 log Internal Server Error: /api/v0/docker/cluster/deploy/
Traceback (most recent call last):
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/Workspace/ilef_cloud/cloud_providers/views.py", line 839, in post
    ports = inspect_image(image=docker_image_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/Workspace/ilef_cloud/cloud_providers/services/shared.py", line 9, in inspect_image
    ports = image_info[0].get('Config', {}).get('ExposedPorts', {})
            ~~~~~~~~~~^^^
IndexError: list index out of range
DEBUG 2024-06-06 12:38:28,448 utils (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 12:38:31,274 log Internal Server Error: /api/v0/docker/cluster/deploy/
DEBUG 2024-06-06 12:39:08,564 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 12:39:15,278 log Internal Server Error: /api/v0/docker/cluster/deploy/
DEBUG 2024-06-06 12:39:39,688 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 12:39:47,686 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 12:39:51,456 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 12:39:58,394 log Internal Server Error: /api/v0/docker/cluster/deploy/
DEBUG 2024-06-06 12:40:55,891 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 12:43:41,773 log Internal Server Error: /api/v0/docker/cluster/deploy/
DEBUG 2024-06-06 12:47:20,719 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 12:54:33,906 log Internal Server Error: /api/v0/docker/cluster/deploy/
Traceback (most recent call last):
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/renderers.py", line 99, in render
    ret = json.dumps(
          ^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/home/mahrezbh/Desktop/pfe/providers_env/lib/python3.12/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ManagedCluster is not JSON serializable
DEBUG 2024-06-06 13:03:10,966 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 13:03:47,101 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 13:04:13,926 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 13:16:08,019 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 13:23:09,474 log Internal Server Error: /api/v0/docker/cluster/deploy/
DEBUG 2024-06-06 13:27:49,773 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 13:28:05,031 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 13:34:33,277 log Internal Server Error: /api/v0/docker/cluster/deploy/
DEBUG 2024-06-06 13:39:26,475 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 13:47:05,016 log Internal Server Error: /api/v0/docker/cluster/deploy/
DEBUG 2024-06-06 13:49:53,266 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 13:50:17,003 utils (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 14:05:01,387 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 14:05:44,471 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 14:05:50,392 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 14:11:41,763 log Internal Server Error: /api/v0/docker/cluster/deploy/
DEBUG 2024-06-06 14:12:45,554 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 14:18:54,593 log Internal Server Error: /api/v0/docker/cluster/deploy/
DEBUG 2024-06-06 14:23:14,755 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 15:09:31,675 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 15:13:31,652 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 16:01:12,846 utils (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 16:01:18,166 log Internal Server Error: /api/v0/azure/clusters/
DEBUG 2024-06-06 16:02:59,395 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 16:08:22,629 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 16:16:30,933 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 16:16:42,548 log Internal Server Error: /api/v0/azure/clusters/
DEBUG 2024-06-06 16:17:20,663 utils (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 16:22:09,636 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 16:24:53,871 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 22:40:28,215 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 22:49:08,706 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 22:51:27,444 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 22:52:06,919 log Internal Server Error: /api/v0/aws/clusters/
DEBUG 2024-06-06 22:52:13,912 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 22:52:16,980 log Internal Server Error: /api/v0/aws/clusters/
DEBUG 2024-06-06 22:55:44,092 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 22:55:47,104 log Internal Server Error: /api/v0/aws/clusters/
ERROR 2024-06-06 22:57:33,547 log Internal Server Error: /api/v0/aws/clusters/
ERROR 2024-06-06 22:58:35,615 log Internal Server Error: /api/v0/aws/clusters/
ERROR 2024-06-06 23:03:09,433 log Internal Server Error: /api/v0/aws/clusters/create/
WARNING 2024-06-06 23:03:22,419 log Method Not Allowed: /api/v0/aws/clusters/create/
DEBUG 2024-06-06 23:03:55,157 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 23:03:57,513 log Internal Server Error: /api/v0/aws/clusters/create/
DEBUG 2024-06-06 23:06:22,882 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 23:09:53,550 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
WARNING 2024-06-06 23:10:25,164 log Bad Request: /api/v0/aws/clusters/create/
DEBUG 2024-06-06 23:10:47,438 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 23:10:51,390 log Internal Server Error: /api/v0/aws/clusters/create/
DEBUG 2024-06-06 23:12:36,757 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 23:12:41,067 log Internal Server Error: /api/v0/aws/clusters/create/
DEBUG 2024-06-06 23:14:28,829 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
DEBUG 2024-06-06 23:14:33,371 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 23:14:38,136 log Internal Server Error: /api/v0/aws/clusters/create/
DEBUG 2024-06-06 23:17:14,083 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 23:17:20,968 log Internal Server Error: /api/v0/aws/clusters/create/
DEBUG 2024-06-06 23:20:13,569 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 23:20:38,599 log Internal Server Error: /api/v0/aws/clusters/create/
ERROR 2024-06-06 23:21:07,286 log Internal Server Error: /api/v0/aws/clusters/create/
DEBUG 2024-06-06 23:23:23,927 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 23:23:43,486 log Internal Server Error: /api/v0/aws/clusters/create/
DEBUG 2024-06-06 23:24:54,451 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 23:25:11,149 log Internal Server Error: /api/v0/aws/clusters/create/
DEBUG 2024-06-06 23:26:53,838 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 23:27:06,736 log Internal Server Error: /api/v0/aws/clusters/create/
DEBUG 2024-06-06 23:40:24,033 utils (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None; alias=default
ERROR 2024-06-06 23:49:13,245 log Internal Server Error: /api/v0/aws/clusters/create/
